### ISSUE TITLE
Include requirements in setup.py

### ISSUE THREAD

**Issue by stuaxo** [karstenw/photobotlib#1]
It would be good if installing this also installed the requirements (Pillow) when installing.

**Comment by karstenw** [comment]
Never done this before. Works on py3 but tries to install the wrong version (8.* instead of last py2 6.2.2) for py2. Needs more learning on my side.

**Comment by karstenw** [comment]
Works.

**Comment by karstenw** [comment]
Installing Pillow < current makes the Security watchdog barf.
